composition:
  name: KVQueue
systems:
  queue:
    type: BaseQueue
    delivery: at_most_once
    max_size: 10

  kv:
    type: BaseKV
    consistency: strong
    conditional_writes: true
    idempotent_writes: true
    max_size: 10
